version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/app/src
    command: python /app/src/main.py
    environment:
      - PYTHONUNBUFFERED=1
    tty: true